captcha:
  height: 80
  width: 240
  length: 6
  max_skew: 0.7
  dot_count: 80
email:
  host: smtp.qq.com
  port: 465
  from: ***
  nickname: ***
  secret: ***
  is_ssl: true
es:
  url: http://***:***
  username: ""
  password: ""
  is_console_print: true
gaode:
  enable: true
  key: ***
jwt:
  access_token_secret: ***
  refresh_token_secret: ***
  access_token_expiry_time: 2h
  refresh_token_expiry_time: 7d
  issuer: go_blog
mysql:
  host: ***
  port: ***
  config: charset=utf8mb4&parseTime=True&loc=Local
  db_name: blog_db
  username: root
  password: ***
  max_idle_conns: 10
  max_open_conns: 100
  log_mode: info
qiniu:
  zone: z0
  bucket: xxx
  img_path: https://xxx.xxx/
  access_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  use_https: true
  use_cdn_domains: true
qq:
  enable: false
  app_id: "***"
  app_key: ***
  redirect_uri: http://***:***/login?flag=qq
redis:
  address: ***:***
  password: ""
  db: 0
system:
  host: 0.0.0.0
  port: 8081
  env: release
  router_prefix: api
  use_multipoint: true
  sessions_secret: ***
  oss_type: local
upload:
  size: 20
  path: uploads
website:
  logo: ""
  full_logo: ""
  title: ***
  slogan: ***
  slogan_en: ***
  description: ***
  version: 1.0.0
  created_at: "***"
  icp_filing: ***
  public_security_filing: ***
  bilibili_url: https://space.bilibili.com/***
  github_url: https://github.com/***
  steam_url: https://steamcommunity.com/profiles/***/
  name: ***
  job: ***
  address: ***
  email: ***
  qq_image: ""
  wechat_image: ""
zap:
  level: info
  filename: log/go_blog.log
  max_size: 200
  max_backups: 30
  max_age: 5
  is_console_print: true
